apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-parent-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Eriln/test'
    path: 'parent-app'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  infos:
    - name: description
      value: 'This application manages other Argo CD applications.'

