apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: 'guestbook'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: child-app2-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
