apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: 'guestbook'
    targetRevision: HEAD
  destination:
    name: 'test1'
    namespace: child-app1-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

